name: Generate Snake Animation

on:
  schedule:
    # Atualiza diariamente
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: GuilhermeFogolin
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push the Snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
